<?php

namespace ContainerUZtyGkt;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O0GSLqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O0G_SLq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O0G_SLq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.BEFtvyx', NULL, 'Cannot determine controller argument for "App\\Controller\\QrcodeController::add()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".'],
        ], [
            'request' => '?',
        ]);
    }
}
