<?php

namespace Container3Oh0x65;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KkPZwLpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kkPZwLp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kkPZwLp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serializer' => ['services', 'serializer', 'getSerializerService', true],
            'user' => ['privates', '.errored..service_locator.kkPZwLp.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.kkPZwLp": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'serializer' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
