<?php

namespace ContainerJVdNJcl;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFirmaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..aBUjoJ.App\Entity\Firma' shared service.
     *
     * @return \App\Entity\Firma
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..aBUjoJ": it references class "App\\Entity\\Firma" but no such service exists.');
    }
}
