<?php

namespace ContainerQWgwCxe;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pm9CmXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pm9CmX_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pm9CmX_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FirmaController::POST_GET_FIRMA_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\PunkteController::GET_Punkte_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\QrcodeController::Add_QrCode_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\RabattController::GET_Rabatt_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\StandortController::POST_GET_FIRMA_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\UserController::POST_GET_User_API' => ['privates', '.service_locator.B4rh_NB', 'get_ServiceLocator_B4rhNBService', true],
            'App\\Controller\\UserRabattController::GET_Userrabatte_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\UserRabattController::Use_Userrabatte_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\FirmaController:POST_GET_FIRMA_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\PunkteController:GET_Punkte_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\QrcodeController:Add_QrCode_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\RabattController:GET_Rabatt_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\StandortController:POST_GET_FIRMA_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\UserController:POST_GET_User_API' => ['privates', '.service_locator.B4rh_NB', 'get_ServiceLocator_B4rhNBService', true],
            'App\\Controller\\UserRabattController:GET_Userrabatte_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\UserRabattController:Use_Userrabatte_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\FirmaController::POST_GET_FIRMA_API' => '?',
            'App\\Controller\\PunkteController::GET_Punkte_API' => '?',
            'App\\Controller\\QrcodeController::Add_QrCode_API' => '?',
            'App\\Controller\\RabattController::GET_Rabatt_API' => '?',
            'App\\Controller\\StandortController::POST_GET_FIRMA_API' => '?',
            'App\\Controller\\UserController::POST_GET_User_API' => '?',
            'App\\Controller\\UserRabattController::GET_Userrabatte_API' => '?',
            'App\\Controller\\UserRabattController::Use_Userrabatte_API' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\FirmaController:POST_GET_FIRMA_API' => '?',
            'App\\Controller\\PunkteController:GET_Punkte_API' => '?',
            'App\\Controller\\QrcodeController:Add_QrCode_API' => '?',
            'App\\Controller\\RabattController:GET_Rabatt_API' => '?',
            'App\\Controller\\StandortController:POST_GET_FIRMA_API' => '?',
            'App\\Controller\\UserController:POST_GET_User_API' => '?',
            'App\\Controller\\UserRabattController:GET_Userrabatte_API' => '?',
            'App\\Controller\\UserRabattController:Use_Userrabatte_API' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
