<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'password' => [[], ['_controller' => 'App\\Controller\\PasswordController::index'], [], [['text', '/password']], [], []],
    'qrcode' => [[], ['_controller' => 'App\\Controller\\QrcodeController::index'], [], [['text', '/qrcode']], [], []],
    'showAll_qrcodes' => [[], ['_controller' => 'App\\Controller\\QrcodeController::showAll'], [], [['text', '/qrcode/showAll/']], [], []],
    'new_qrcode_form' => [[], ['_controller' => 'App\\Controller\\QrcodeController::add'], [], [['text', '/qrcode/new']], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], []],
    'show_user' => [[], ['_controller' => 'App\\Controller\\UserController::showUser'], [], [['text', '/user/show}']], [], []],
    'new_user_Form' => [[], ['_controller' => 'App\\Controller\\UserController::addUser'], [], [['text', '/user/new}']], [], []],
];
