<?php

namespace ContainerGjlDJHp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5lI18gAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5lI18gA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5lI18gA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DesignController::checkAutomagic' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\FirmaController::Firma_API' => ['privates', '.service_locator..aBUjoJ', 'get_ServiceLocator__ABUjoJService', true],
            'App\\Controller\\PunkteController::Punkte_API' => ['privates', '.service_locator.kkPZwLp', 'get_ServiceLocator_KkPZwLpService', true],
            'App\\Controller\\QrcodeController::Add_QrCode_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\RabattController::Rabatt_API' => ['privates', '.service_locator..aBUjoJ', 'get_ServiceLocator__ABUjoJService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\DesignController:checkAutomagic' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\FirmaController:Firma_API' => ['privates', '.service_locator..aBUjoJ', 'get_ServiceLocator__ABUjoJService', true],
            'App\\Controller\\PunkteController:Punkte_API' => ['privates', '.service_locator.kkPZwLp', 'get_ServiceLocator_KkPZwLpService', true],
            'App\\Controller\\QrcodeController:Add_QrCode_API' => ['privates', '.service_locator.jGCCKtX', 'get_ServiceLocator_JGCCKtXService', true],
            'App\\Controller\\RabattController:Rabatt_API' => ['privates', '.service_locator..aBUjoJ', 'get_ServiceLocator__ABUjoJService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\DesignController::checkAutomagic' => '?',
            'App\\Controller\\FirmaController::Firma_API' => '?',
            'App\\Controller\\PunkteController::Punkte_API' => '?',
            'App\\Controller\\QrcodeController::Add_QrCode_API' => '?',
            'App\\Controller\\RabattController::Rabatt_API' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DesignController:checkAutomagic' => '?',
            'App\\Controller\\FirmaController:Firma_API' => '?',
            'App\\Controller\\PunkteController:Punkte_API' => '?',
            'App\\Controller\\QrcodeController:Add_QrCode_API' => '?',
            'App\\Controller\\RabattController:Rabatt_API' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
