<?php

namespace ContainerIEdISJ5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B4rhNBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B4rh_NB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B4rh_NB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', true],
        ], [
            'mailer' => '?',
            'serializer' => '?',
        ]);
    }
}
