<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVuXFLsm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVuXFLsm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVuXFLsm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVuXFLsm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVuXFLsm\App_KernelDevDebugContainer([
    'container.build_hash' => 'VuXFLsm',
    'container.build_id' => 'b1c881da',
    'container.build_time' => 1604940790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVuXFLsm');
