<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI5KndoY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI5KndoY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI5KndoY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI5KndoY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI5KndoY\App_KernelDevDebugContainer([
    'container.build_hash' => 'I5KndoY',
    'container.build_id' => '1014a2b9',
    'container.build_time' => 1610386930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI5KndoY');
