<?php

namespace ContainerQOJLoTi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAngestellteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AngestellteRepository' shared autowired service.
     *
     * @return \App\Repository\AngestellteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AngestellteRepository'] = new \App\Repository\AngestellteRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
