<?php

namespace ContainerQOJLoTi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PasswordType' shared autowired service.
     *
     * @return \App\Form\PasswordType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PasswordType'] = new \App\Form\PasswordType();
    }
}
