<?php

namespace ContainerQOJLoTi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQRCodeTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\QRCodeType' shared autowired service.
     *
     * @return \App\Form\QRCodeType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\QRCodeType'] = new \App\Form\QRCodeType();
    }
}
