<?php

namespace ContainerQOJLoTi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQrcodeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\QrcodeRepository' shared autowired service.
     *
     * @return \App\Repository\QrcodeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\QrcodeRepository'] = new \App\Repository\QrcodeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
