<?php

namespace ContainerQOJLoTi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQrcodeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\QrcodeController' shared autowired service.
     *
     * @return \App\Controller\QrcodeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\QrcodeController'] = $instance = new \App\Controller\QrcodeController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\QrcodeController', $container));

        return $instance;
    }
}
