<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserRabatte extends \App\Entity\UserRabatte implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UserRabatte' . "\0" . 'Rabatt_Code', '' . "\0" . 'App\\Entity\\UserRabatte' . "\0" . 'FK_User_ID', '' . "\0" . 'App\\Entity\\UserRabatte' . "\0" . 'FK_Rabatt_ID'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UserRabatte' . "\0" . 'Rabatt_Code', '' . "\0" . 'App\\Entity\\UserRabatte' . "\0" . 'FK_User_ID', '' . "\0" . 'App\\Entity\\UserRabatte' . "\0" . 'FK_Rabatt_ID'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserRabatte $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRabattCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRabattCode', []);

        return parent::getRabattCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setRabattCode($Rabatt_Code): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRabattCode', [$Rabatt_Code]);

        parent::setRabattCode($Rabatt_Code);
    }

    /**
     * {@inheritDoc}
     */
    public function getFKUserID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFKUserID', []);

        return parent::getFKUserID();
    }

    /**
     * {@inheritDoc}
     */
    public function setFKUserID($FK_User_ID): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFKUserID', [$FK_User_ID]);

        parent::setFKUserID($FK_User_ID);
    }

    /**
     * {@inheritDoc}
     */
    public function getFKRabattID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFKRabattID', []);

        return parent::getFKRabattID();
    }

    /**
     * {@inheritDoc}
     */
    public function setFKRabattID($FK_Rabatt_ID): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFKRabattID', [$FK_Rabatt_ID]);

        parent::setFKRabattID($FK_Rabatt_ID);
    }

}
