<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Betrieb extends \App\Entity\Betrieb implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'FK_Firma_ID', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'Addresse', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'PLZ', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'Ort'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'FK_Firma_ID', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'Addresse', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'PLZ', '' . "\0" . 'App\\Entity\\Betrieb' . "\0" . 'Ort'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Betrieb $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFKFirmaID(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFKFirmaID', []);

        return parent::getFKFirmaID();
    }

    /**
     * {@inheritDoc}
     */
    public function setFKFirmaID(int $FK_Firma_ID): \App\Entity\Betrieb
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFKFirmaID', [$FK_Firma_ID]);

        return parent::setFKFirmaID($FK_Firma_ID);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresse', []);

        return parent::getAddresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddresse(?string $Addresse): \App\Entity\Betrieb
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddresse', [$Addresse]);

        return parent::setAddresse($Addresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getPLZ(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPLZ', []);

        return parent::getPLZ();
    }

    /**
     * {@inheritDoc}
     */
    public function setPLZ(?string $PLZ): \App\Entity\Betrieb
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPLZ', [$PLZ]);

        return parent::setPLZ($PLZ);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrt', []);

        return parent::getOrt();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrt(?string $Ort): \App\Entity\Betrieb
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrt', [$Ort]);

        return parent::setOrt($Ort);
    }

}
