<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Firma extends \App\Entity\Firma implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'FK_User_ID__Owner', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'Firmanname', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'Kontakt_Email', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'XEuroFuer1Punkt', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'Datei', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'Domain'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'FK_User_ID__Owner', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'Firmanname', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'Kontakt_Email', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'XEuroFuer1Punkt', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'Datei', '' . "\0" . 'App\\Entity\\Firma' . "\0" . 'Domain'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Firma $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFKUserIDOwner(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFKUserIDOwner', []);

        return parent::getFKUserIDOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setFKUserIDOwner(?int $FK_User_ID__Owner): \App\Entity\Firma
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFKUserIDOwner', [$FK_User_ID__Owner]);

        return parent::setFKUserIDOwner($FK_User_ID__Owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirmanname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirmanname', []);

        return parent::getFirmanname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirmanname(string $Firmanname): \App\Entity\Firma
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirmanname', [$Firmanname]);

        return parent::setFirmanname($Firmanname);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontaktEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontaktEmail', []);

        return parent::getKontaktEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setKontaktEmail(?string $Kontakt_Email): \App\Entity\Firma
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKontaktEmail', [$Kontakt_Email]);

        return parent::setKontaktEmail($Kontakt_Email);
    }

    /**
     * {@inheritDoc}
     */
    public function getXEuroFuer1Punkt(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXEuroFuer1Punkt', []);

        return parent::getXEuroFuer1Punkt();
    }

    /**
     * {@inheritDoc}
     */
    public function setXEuroFuer1Punkt(?float $XEuroFuer1Punkt): \App\Entity\Firma
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXEuroFuer1Punkt', [$XEuroFuer1Punkt]);

        return parent::setXEuroFuer1Punkt($XEuroFuer1Punkt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatei()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatei', []);

        return parent::getDatei();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatei($Datei): \App\Entity\Firma
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatei', [$Datei]);

        return parent::setDatei($Datei);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', []);

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain(string $Domain): \App\Entity\Firma
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', [$Domain]);

        return parent::setDomain($Domain);
    }

}
